spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm_demo_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 1970j327@Ts
debug: true
mybatis:
  type-aliases-package: com.hpm.blog.model
  config-location: classpath:mybatis.xml
